# Cyberpunk Alacritty Configuration
[window]
opacity = 0.2
blur = true
decorations = "none"
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 20
y = 20

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
size = 12

[colors]
# Cyberpunk color scheme - dark with neon accents
[colors.primary]
background = "#0a0a0f"
foreground = "#e0e0e0"

[colors.cursor]
text = "#0a0a0f"
cursor = "#ff007f"  # Hot pink cursor

[colors.normal]
black = "#2e2e2e"
red = "#ff0040"     # Neon red
green = "#00ff80"   # Neon green
yellow = "#ffff00"  # Electric yellow
blue = "#0080ff"    # Cyber blue
magenta = "#ff00ff" # Hot magenta
cyan = "#00ffff"    # Electric cyan
white = "#e0e0e0"

[colors.bright]
black = "#5e5e5e"
red = "#ff4080"
green = "#40ff90"
yellow = "#ffff40"
blue = "#4090ff"
magenta = "#ff40ff"
cyan = "#40ffff"
white = "#ffffff"

# Selection colors
[colors.selection]
text = "#0a0a0f"
background = "#ff007f"

# URL colors
[colors.hints]
start = { foreground = "#ff007f", background = "#0a0a0f" }
end = { foreground = "#00ffff", background = "#0a0a0f" }

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
]
